# Specifies the version of the Docker Compose file format.
version: '3.8'

# This is the main section where we define our containers (services).
services:
  # Defines our Python application service.
  app:
    # Tells Compose to build the Docker image from the Dockerfile in the current directory ('.').
    build: .
    # Sets a custom name for the container for easy identification.
    container_name: url-shortener-app
    # Maps port 3333 on your Mac to port 3333 inside the container.
    ports:
      - "3333:3333"
    # This is crucial: it tells the app how to find the Redis container.
    # The hostname 'redis' is automatically available on the internal network Compose creates.
    environment:
      - REDIS_HOST=redis
    # Makes sure the 'redis' service is started BEFORE this 'app' service.
    depends_on:
      - redis
    # Attaches this service to our custom network.
    networks:
      - url-net

  # Defines our Redis database service.
  redis:
    # Pulls a lightweight version of the Redis image from Docker Hub.
    image: "redis:alpine"
    # Sets a custom name for the container.
    container_name: url-shortener-redis
    # Attaches this service to our custom network.
    networks:
      - url-net

# Defines the custom network our containers will use to communicate.
networks:
  url-net:
    driver: bridge
